#!/bin/sh
# phantom-server entrypoint
#
# Bootstrap policy:
#   - Если /config/server.toml существует — стартуем как есть (восстановление из бэкапа).
#   - Если /config/server.toml нет — генерируем fresh state: CA + server-cert,
#     рендерим server.toml из шаблона с подстановкой ENV (SERVER_NAME, WAN_IFACE,
#     ADMIN_TOKEN), пишем пустой clients.json.

set -eu

CONFIG_DIR="${CONFIG_DIR:-/config}"
SERVER_TOML="${CONFIG_DIR}/server.toml"
CA_CRT="${CONFIG_DIR}/ca.crt"
CLIENTS_JSON="${CONFIG_DIR}/clients.json"

mkdir -p "$CONFIG_DIR"

if [ ! -f "$SERVER_TOML" ]; then
    echo "[bootstrap] $SERVER_TOML missing — running first-boot setup"

    if [ -z "${SERVER_NAME:-}" ]; then
        echo "[bootstrap] FATAL: SERVER_NAME env var must be set on first boot (TLS SNI / cert CN)" >&2
        echo "[bootstrap]        Either set it in .env or place a prepared server.toml into ./config/" >&2
        exit 1
    fi

    WAN_IFACE="${WAN_IFACE:-eth0}"
    TUN_NAME="${TUN_NAME:-tun1}"
    TUN_ADDR="${TUN_ADDR:-10.7.0.1/24}"
    LISTEN_ADDR="${LISTEN_ADDR:-0.0.0.0:443}"
    ADMIN_LISTEN="${ADMIN_LISTEN:-10.7.0.1:8080}"

    if [ -z "${ADMIN_TOKEN:-}" ]; then
        ADMIN_TOKEN="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
        echo "[bootstrap] Generated ADMIN_TOKEN: $ADMIN_TOKEN"
        echo "[bootstrap] Save it — it lets you call the admin API via VPN tunnel."
    fi

    if [ ! -f "$CA_CRT" ]; then
        echo "[bootstrap] Generating CA + server certificate via phantom-keygen"
        phantom-keygen --out "$CONFIG_DIR" --server-name "$SERVER_NAME"
    else
        echo "[bootstrap] CA already in $CONFIG_DIR — keeping it, only regenerating server.toml"
    fi

    if [ ! -f "$CLIENTS_JSON" ]; then
        echo '{"clients":{}}' > "$CLIENTS_JSON"
        echo "[bootstrap] Wrote empty $CLIENTS_JSON"
    fi

    cat > "$SERVER_TOML" <<EOF
# Generated by docker entrypoint on first boot.
# Safe to edit; container will not overwrite once this file exists.

[network]
listen_addr = "${LISTEN_ADDR}"
tun_name    = "${TUN_NAME}"
tun_addr    = "${TUN_ADDR}"
tun_mtu     = 1350
wan_iface   = "${WAN_IFACE}"

[h2]
listen_addr = "${LISTEN_ADDR}"

[timeouts]
idle_timeout_secs = 300
hard_timeout_secs = 86400

[quic]
cert_subjects        = ["${SERVER_NAME}"]
ca_cert_path         = "${CA_CRT}"
allowed_clients_path = "${CLIENTS_JSON}"
idle_timeout_secs    = 30

[admin]
listen_addr  = "${ADMIN_LISTEN}"
token        = "${ADMIN_TOKEN}"
ca_cert_path = "${CA_CRT}"
ca_key_path  = "${CONFIG_DIR}/ca.key"
EOF

    echo "[bootstrap] Wrote $SERVER_TOML"
    echo "[bootstrap] First client: docker exec -it phantom-server keys"
else
    echo "[entrypoint] Found existing $SERVER_TOML — skipping bootstrap"
fi

exec phantom-server -c "$SERVER_TOML"
