#!/bin/sh
# phantom-relay entrypoint
#
# Если /config/relay.toml нет — копируем шаблон и рендерим из ENV.
# Если есть — стартуем как есть.

set -eu

CONFIG_DIR="${CONFIG_DIR:-/config}"
RELAY_TOML="${CONFIG_DIR}/relay.toml"

mkdir -p "$CONFIG_DIR"

if [ ! -f "$RELAY_TOML" ]; then
    echo "[bootstrap] $RELAY_TOML missing — generating from env"

    if [ -z "${UPSTREAM_ADDR:-}" ]; then
        echo "[bootstrap] FATAL: UPSTREAM_ADDR must be set on first boot (e.g. nl2.example.com:443)" >&2
        exit 1
    fi
    if [ -z "${EXPECTED_SNI:-}" ]; then
        echo "[bootstrap] FATAL: EXPECTED_SNI must be set on first boot (e.g. relay.example.com)" >&2
        exit 1
    fi

    LISTEN_ADDR="${LISTEN_ADDR:-0.0.0.0:5443}"

    if [ -n "${FALLBACK_CERT:-}" ] && [ -n "${FALLBACK_KEY:-}" ]; then
        FALLBACK_BLOCK="cert_path = \"${FALLBACK_CERT}\"
key_path  = \"${FALLBACK_KEY}\""
    else
        FALLBACK_BLOCK="# fallback disabled — SNI mismatch drops the connection"
    fi

    cat > "$RELAY_TOML" <<EOF
# Generated by docker entrypoint on first boot.

listen_addr   = "${LISTEN_ADDR}"
upstream_addr = "${UPSTREAM_ADDR}"
expected_sni  = "${EXPECTED_SNI}"

${FALLBACK_BLOCK}
EOF
    echo "[bootstrap] Wrote $RELAY_TOML"
else
    echo "[entrypoint] Found existing $RELAY_TOML — skipping bootstrap"
fi

exec phantom-relay --config "$RELAY_TOML"
