#ifndef PHANTOM_CORE_H
#define PHANTOM_CORE_H

/* Generated by cbindgen — do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Start the tunnel runtime.
 *
 * * `cfg_json`      — JSON-encoded [`ConnectProfile`] (name + conn_string + settings).
 * * `settings_json` — JSON-encoded [`TunnelSettings`] (overrides settings inside
 *                     cfg_json if present; may be `null` / empty to use defaults).
 * * `status_cb`     — called on every [`StatusFrame`] change; JSON-encoded bytes.
 * * `log_cb`        — called for every [`LogFrame`]; JSON-encoded bytes.
 * * `outbound_cb`   — called for each IP packet from the tunnel destined to the device.
 * * `ctx`           — opaque pointer forwarded to all three callbacks.
 *
 * Returns 0 on success, negative on error.
 */

int32_t phantom_runtime_start(const char *cfg_json,
                              const char *settings_json,
                              void (*status_cb)(const uint8_t*, uintptr_t, void*),
                              void (*log_cb)(const uint8_t*, uintptr_t, void*),
                              void (*outbound_cb)(const uint8_t*, uintptr_t, void*),
                              void *ctx);

/**
 * Push an outbound IP packet (read from `packetFlow`) into the tunnel.
 *
 * Naming convention note: "inbound" here is from the tunnel's perspective —
 * this packet travels inbound to the tunnel (device → network).
 *
 * Returns 0 on accept, -10 on queue full (drop), -11 if no tunnel running.
 */
 int32_t phantom_runtime_submit_inbound(const uint8_t *ptr, uintptr_t len);

/**
 * Signal the running tunnel to shut down gracefully.
 * Returns 0 if a shutdown was signalled, -11 if no tunnel was running.
 */
 int32_t phantom_runtime_stop(void);

/**
 * Parse a `ghs://...` connection string and return JSON with the iOS-
 * relevant fields: `{"server_addr":"...","server_name":"...","tun_addr":"...",`
 * `"cert_pem":"...","key_pem":"..."}`. Returns NULL on parse error.
 * Caller must free via `phantom_free_string`.
 */
 char *phantom_parse_conn_string(const char *input);

/**
 * Input: text of a CIDR file (one `a.b.c.d/nn` per line — the *contents*,
 * not a path; iOS extension reads the file and passes the string).
 * Output: JSON array `[{"addr":"...","prefix":N}]` of routes that should be
 * sent through the VPN (complement of the direct list).
 * Caller must free via `phantom_free_string`.
 */
 char *phantom_compute_vpn_routes(const char *direct_cidrs);

/**
 * Free a string returned by any `phantom_*` function that returns
 * `*mut c_char`. Passing NULL is a no-op. Passing anything not obtained
 * from this library, or double-freeing, is undefined behavior.
 */
 void phantom_free_string(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PHANTOM_CORE_H */
