#ifndef PHANTOM_CORE_H
#define PHANTOM_CORE_H

/* Generated by cbindgen — do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Start the tunnel. `config_json` is a JSON object:
 * `{"server_addr":"...","server_name":"...","insecure":bool,`
 * ` "cert_pem":"...","key_pem":"...","ca_cert_pem":"..."|null}`
 *
 * Returns 0 on success, negative on error.
 */
 int32_t phantom_start(const char *config_json);

/**
 * Signal the running tunnel to shut down. Non-blocking beyond a brief yield
 * to let the abort propagate. Subsequent `phantom_start` calls reuse the
 * same tokio runtime.
 */
 void phantom_stop(void);

/**
 * Submit an outbound IP packet read from `NEPacketTunnelProvider.packetFlow`.
 * Returns 0 on accept, -10 on queue full (packet dropped), -11 if no tunnel
 * is running, -1 on bad pointer/len.
 */
 int32_t phantom_submit_outbound(const uint8_t *ptr, uintptr_t len);

/**
 * Register a C callback that Rust will invoke for each inbound IP packet
 * decoded from the TLS streams. Pass `cb=None` to clear.
 *
 * The `ctx` pointer is stored and passed back verbatim. The caller must keep
 * it valid until a subsequent call replaces it.
 */
 void phantom_set_inbound_callback(void (*cb)(const uint8_t*, uintptr_t, void*), void *ctx);

/**
 * Returns a newly-allocated JSON string:
 * `{"bytes_rx":N,"bytes_tx":N,"pkts_rx":N,"pkts_tx":N,"connected":bool}`.
 * Caller must free via `phantom_free_string`.
 */
 char *phantom_get_stats(void);

/**
 * Returns a JSON array of log entries with `seq > since_seq`. Pass -1 to
 * get everything in the ring buffer.
 * Shape: `[{"seq":N,"ts":"HH:MM:SS","level":"INFO","msg":"..."}]`.
 * Caller must free via `phantom_free_string`.
 */
 char *phantom_get_logs(int64_t since_seq);

/**
 * Accepts "trace", "debug", "info", "warn", "error" (case-insensitive).
 * Unknown strings reset to "info".
 */
 void phantom_set_log_level(const char *level);

/**
 * Parse a `ghs://...` connection string and return JSON with the iOS-
 * relevant fields: `{"server_addr":"...","server_name":"...","tun_addr":"...",`
 * `"cert_pem":"...","key_pem":"..."}`. Returns NULL on parse error.
 * Caller must free via `phantom_free_string`.
 */
 char *phantom_parse_conn_string(const char *input);

/**
 * Input: text of a CIDR file (one `a.b.c.d/nn` per line — the *contents*,
 * not a path; iOS extension reads the file and passes the string).
 * Output: JSON array `[{"addr":"...","prefix":N}]` of routes that should be
 * sent through the VPN (complement of the direct list).
 * Caller must free via `phantom_free_string`.
 */
 char *phantom_compute_vpn_routes(const char *direct_cidrs);

/**
 * Free a string returned by any `phantom_*` function that returns
 * `*mut c_char`. Passing NULL is a no-op. Passing anything not obtained
 * from this library, or double-freeing, is undefined behavior.
 */
 void phantom_free_string(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PHANTOM_CORE_H */
