[network]
server_addr = "SERVER_PUBLIC_IP:3478"
tun_name    = "tun0"
tun_addr    = "10.7.0.2/24"
tun_mtu     = 1380
default_gw  = "10.7.0.1"

[keys]
client_private_key = "REPLACE_ME_BASE64_CLIENT_PRIVATE_KEY"
client_public_key  = "REPLACE_ME_BASE64_CLIENT_PUBLIC_KEY"
server_public_key  = "REPLACE_ME_BASE64_SERVER_PUBLIC_KEY"
shared_secret      = "REPLACE_ME_BASE64_32_BYTE_SHARED_SECRET"
