[network]
server_addr = "89.110.109.128:3478"
tun_name    = "tun0"
tun_addr    = "10.7.0.2/24"
tun_mtu     = 1380
default_gw  = "10.7.0.1"

[keys]
client_private_key = "ABZzsnfYTnnuA84gpoqRtmhC68BQqjU9fggZ7ja2oHY="
client_public_key  = "BRK57xg3Z8qHVGpl3UfzNzK+ejUtbW4+UftWquO8YHA="
server_public_key  = "xyfuFjuTYKub6mnNwuGArdSdWJPANrAzgEZ5OK+qUQs="
shared_secret      = "uOIwTeL7NcAK/9JhC4MIklPmoLnPz1kJjAWGPFn5FQ0="
